### ISSUE TITLE
We would like to create an empty multicast block under an address

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#128]
##### SUMMARY

We would like to create an empty multicast block bellow an address in the Artemis configuration, in essence a topic with no consumers yet. The consumers will create the queues themselves but are not allowed to create addresses. Customers create these queues dynamically. This needed since a queue created on a multicast address with no consumers will keep the messages on the address forever. 

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE
We tested this configuration but it doesn't work:, the rest is default 
```
activemq_addresses:
  - name: importantTopic
      multicast:

```

##### EXPECTED RESULTS
We expect this to end up in the broker.xml (should be possible according to the documentation, This example https://activemq.apache.org/components/artemis/documentation/2.0.0/address-model.html. )

```
<configuration ...>
  <core ...>
    ...
    <address name="importantTopic">
      <multicast/>
    </address>
  </core>
</configuration>
```
##### ACTUAL RESULTS
We got validation errors we were not able to create it, It seems this template does not allow for an empty multicast block:
https://github.com/ansible-middleware/amq/blob/main/roles/activemq/templates/addresses.broker.xml.j2 

This is holding back a production release of our broker so it would be nice if it can be fixed soon

**Comment by guidograzioli** [comment]
Reproduced, working on fix
