### ISSUE TITLE
Shared data disk should not be in the same folder as amq-broker program files

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#14]
##### SUMMARY
Currently, the shared storage for an HA-shared storage setup is stored in `/opt/amq/amq-broker/data/shared.`  I believe it would be best practice to store the data in a separate folder from the AMQ program files (/`opt/amq/amq-broker.` This would make two things easier: 
- Recursive permission management for the whole folder (this is not possible for NFS mounts)
- Performing a clean install for development in which you delete the program folder but not the data folder. 

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Making [this variable](https://github.com/ansible-middleware/amq/blob/main/roles/amq_broker/defaults/main.yml#L89) represent an absolute path would tackle this
