### ISSUE TITLE
Publish the Federation feature to RedHat Automation Hub

### ISSUE THREAD

**Issue by seravat** [ansible-middleware/amq#140]
##### SUMMARY
This repo already has the possibility of adding Federations to the AMQ config, but that is not published on RedHat Automation Hub or to Ansible Galaxy.

Could this be published soon?

**Comment by guidograzioli** [comment]
Hello thanks for asking; 2.1.0 will hit galaxy today or tomorrow, it will take somewhat longer to get into automation hub.

**Comment by seravat** [comment]
Perfect! Thanks

**Comment by guidograzioli** [comment]
2.1.1 is on autoamtion hub
