### ISSUE TITLE
Removing an address from the variable does not remove the address

### ISSUE THREAD

**Issue by michie1** [ansible-middleware/amq#148]
##### SUMMARY
I try to remove an address by omitting an element in the list `amq_broker_addresses`. The address xml tag is removed in the `broker.xml`, but via the webconsole it can be seen the address does still exist. Even after a full service restart.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.15.12]
```

##### COLLECTION VERSION
Note: I'm using the https://console.redhat.com/ansible/automation-hub/repo/published/redhat/amq_broker/ this role, with AMQ broker version 7.11.
```
redhat.amq_broker             2.0.1
```

##### STEPS TO REPRODUCE
See summary.

##### EXPECTED RESULTS
I expected the address to not be shown anymore in the webconsole.

##### ACTUAL RESULTS
The address is still visible in the webconsole.

**Comment by guidograzioli** [comment]
Seems a webconsole caching problem, or some downstream bug, I'll try to reproduce

**Comment by michie1** [comment]
No bug! Solved it by setting `config-delete-addresses`  to `FORCE` (https://activemq.apache.org/components/artemis/documentation/latest/config-reload.html#configuration-reload ) in the address settings.
