### ISSUE TITLE
SSL for connectors and acceptors in broker.xml. 

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#15]
##### SUMMARY
The current options to enable SSL do not enable SSL for connectors and acceptors in broker.xml. Currently, SSL settings only implement SSL settings for the Web UI. It would be preferable to also implement SSL settings for acceptors and connectors by using this playbook. Would this be possible in the future? 

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Hello Robert, this is definitely at top of the roadmap; the work on this collection just started, you are welcome to point out anything you'd find useful

**Comment by guidograzioli** [comment]
PR #30 and #31 address acceptor/connector TLS
