### ISSUE TITLE
Refuse to run on non-RHEL OSes

### ISSUE THREAD

**Issue by feld** [ansible-middleware/amq#172]
It's not clear from the description that these playbooks are very RHEL-specific (rpm, dnf, /etc/sysconfig usage, etc) and is not tested on Debian/Ubuntu at all.

Please make the playbook refuse to run on distros that are not supported. I was about to send a PR to remove the use of /etc/sysconfig and then I discovered it's unlikely this playbook will completely work without further changes...

**Comment by guidograzioli** [comment]
The roles are rhel family specific ( https://github.com/ansible-middleware/amq/blob/main/roles/activemq/meta/main.yml#L17 ) while the modules/plugins are general
