### ISSUE TITLE
Update crypto algorithm 

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#77]
##### SUMMARY
The security team asked us to improve the algorithms used to hash and salt the passwords when they are masked on the filesystem. They would like us to configure/decide the following parameters (at minimum): iterations, randomScheme & sceretKeyAlgorithm.

Rationale:

We do not accept the use of the SHA1 cipher anywhere, because we deem it insecure and unfit for production use. 

The amount of PBKDF2 rounds is too small, this makes comprise too “computationally” easy. PBKDF relies on a “work” (iteration) factor, which is a weak paradigm, however given proper iteration counts we deem the risk med/low.

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
I think it makes sense, the first iteration for the pbkdf2 filter was to mimic activemq default, it will be no problem to open up the parameters for the underlying hashlib call.

**Comment by guidograzioli** [comment]
The linked changed provides the feature but please mind the notes and the minimum versions required!

**Comment by guidograzioli** [comment]
Hello Robert; it's definitely the java codec class spitting its log to standard output. Which class are you using? Can I see it?

**Comment by RobertFloor** [comment]
hi where can I find that?

**Comment by guidograzioli** [comment]
I guess you are using default codec class; it does not support changing iterations or algorithm, you will need to provide your own class. Please go thru this documentation attached to the PR:
https://github.com/ansible-middleware/amq/pull/95
In particular the two NOTEs at the end

**Comment by guidograzioli** [comment]
AMQ 7.11.1 is based on 2.28, but got the necessary fix backported into it, so it's good.

The  JBoss logmanager stacktrace is weird, it is not supposed to be use anymore in activemq >= 28. Was it run in an upgraded instance? Maybe some the upgrade missed some changes

**Comment by RobertFloor** [comment]
Hi thanks for the response. I have it working, but a weird combo with the Metrics plugin creates a problem. 

This works 
```
[root@amq1 bin]# ./artemis mask --password-codec --hash test
2023-09-08 14:37:19,168 INFO  [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}
result: c5a9a21e812fea2794df0114fa7c78b0:a52d7c2dff4a36c7b4ed381b067872b154e88e0b0017ec9a53defdbe865b67161bf4b32f0c22e6928a015afcc5aef512ab0b55f0237f459a39ad5025713aecf6
```
But logging ends up in the  artemis.users file
```
amq-admin = ENC(2023-09-08 14:35:33,856 INFO  [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}
63657b38db1a65d197efd58a56af275c:b6a4fc05591317fd0bc95c7c5a3dbd6ab41764b93cd51aa31a8efb90c9f6ed712dc5d49a7cafc2d90f4e5bce30683aeb7b8160ae19791baf1edd8498bbab41d3)
amq-application-sa = ENC(2023-09-08 14:35:38,378 INFO  [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}
f42e63958b97a33141455b2265e04b25:b12c5cb6fbc0adf9d21027473a3d9c7eb16e8c98d6fc4d6c6cfcee53ba1faba47ac3855ef12af9fa82bd673b69d0fddb4ebb4d076e03f10e4bfca1dd0e29e09c)
amq-testers-sa = ENC(2023-09-08 14:35:42,274 INFO  [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}
c11e766e2c53940384a1000c908a9be8:238040adcb3a10d85abe2fc6dd136578cec1e8844a173fdde4ad9ed40e3d5df7f017bcb8f1bad4da177dd3b2b2dde5ff9d03500b7600c2375b17ad4b8eaaeebf)
```

The logging suggests there is a problem with ArtemisPrometheusMetricsPlugin. When I remove this from the broker.xml 
```
    <metrics>
      <plugin class-name="com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin"/>
    </metrics>
```
I get a password mask command without logging
```
[root@amq1 bin]# ./artemis mask --password-codec --hash test
result: 5904b58f3a1475b931823395d439069c:2c12c60c736f6a6be94aed1172a67060bc887b7575eebdad54325df76995f9cbabcb220745059502a2f478e7dd4c26747c1b4bd484dc9e939c7fb49cd90263aa
```
