### ISSUE TITLE
Provide a custom login.config

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#80]
##### SUMMARY
We would like to enable logging in to the Broker via LDAP provide our own `login.config` template file for the playbook to allow logging in via LDAP. Would this be possible?

##### ISSUE TYPE
 - Feature Idea

**Comment by RobertFloor** [comment]
Preferably we would like to mask the password we add to this file too

**Comment by RobertFloor** [comment]
We also need the option     
`useStartTLS="true";`

**Comment by guidograzioli** [comment]
> -In our case the LDAP module is sufficient, we would like to allow for local login in case of emergency (no LDAP connection)

You can achieve that by letting both `activemq_auth_properties_enabled` and `activemq_auth_ldap_enabled` be True: properties will be `sufficient` and ldap `required`, so that local emergency account logins are attempted first in case ldap connectivity is down.

> -More importantly you need to make sure the password is between quotes otherwise you get this error:

good find!

**Comment by guidograzioli** [comment]
Fixed in HEAD

**Comment by RobertFloor** [comment]
fixes it thank it :)
