### ISSUE TITLE
We would like to be able to configure the JVM arguments -Xms and -Xmx

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#89]
##### SUMMARY
We want to be able to configure the JVM arguments -Xms and -Xmx to set server available RAM. For a high load, our servers production need more heap memory. This is also recommended here https://activemq.apache.org/components/artemis/documentation/2.1.0/perf-tuning.html. Therefore we would like to configure these settings. 

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Hi Robert, have you tried overriding the following default? (you'll need to override the whole list though):
https://github.com/ansible-middleware/amq/blob/main/roles/activemq/defaults/main.yml#L33

**Comment by RobertFloor** [comment]
Hi thanks this works for use
