### ISSUE TITLE
We want to be able to change the broker's name in the broker.xml, but without changing the name of all folders and others

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#90]
##### SUMMARY
We want to be able to change the broker's name in the broker.xml, but without changing the name of all folders, the systemd unit file. The name change of the broker would improve te readability of our log, but having a different folder structure for each broker would be very difficult to manage. 

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
Do you mean changing the following only? 
https://github.com/ansible-middleware/amq/blob/main/roles/activemq/files/artemis-configuration-2.28.xsd#L34
I am not sure it will have impact on the logfiles except for the `AMQ221001` line (?)

**Comment by RobertFloor** [comment]
For us this no longer has the highest priority
